services:
  - type: web
    name: dhansaathi-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20.12.0

  - type: web
    name: market-service
    env: node
    rootDir: market-service
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.12.0
      - key: PORT
        value: 10000
